In [ ]:
import numpy as np

A = np.random.randint(10, size=(3, 3))
print(A)

B =  np.random.randint(10, size=(3, 3))
print(B)

c =  np.random.randint(10, size=(3, 2))
print(c)

d =  np.random.randint(10, size=(3, 3))
print(d)
B_T = B.transpose()
print('transpose')
print(B_T)
C = 2
D = 4
g = (C + D)*A
h = (C*A) + (D*A)
print(g)

[[8 1 4]
 [3 2 7]
 [3 5 8]]
[[1 1 1]
 [3 1 1]
 [1 8 3]]
[[0 7]
 [7 3]
 [0 5]]
[[3 8 7]
 [9 7 0]
 [2 5 0]]
transpose
[[1 3 1]
 [1 1 8]
 [1 1 3]]
[[48  6 24]
 [18 12 42]
 [18 30 48]]


In [ ]:
C = 2
D = 4
g = (C + D)*A # penjumlahan matriks
h = (C*A) + (D*A)
print(g)

[[48 30  0]
 [36 48 30]
 [36  0 54]]


In [ ]:
k = A + B
L = A + C
print(k)
print(L)

[[11 13  7]
 [ 8 16 11]
 [12  7 17]]
[[10  7  2]
 [ 8 10  7]
 [ 8  2 11]]


In [ ]:
v = A - B
print(v)
o = A@c # perkalian matriks
print(o)
# membuat program perkalian matriks

[[ 5 -3 -7]
 [ 4  0 -1]
 [ 0 -7  1]]
[[ 20 117]
 [ 37 141]
 [  9  81]]


In [ ]:
# mencari matriks transpose
c_T = c.transpose()
print(c_T)
u = c@c_T # menjumlahkan matriks transpose
print(u)
u.shape

[[0 7 0]
 [7 3 5]]
[[49 21 35]
 [21 58 15]
 [35 15 25]]


(3, 3)

In [1]:
B.transpose = np.transpose()
print(B.transpose)

NameError: name 'np' is not defined